export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const MFA_CODE_REQUIRED = 'MFA_CODE_REQUIRED';
export const PASSWORD_RESET_REQUIRED = 'PASSWORD_RESET_REQUIRED';
